# Generated by Django 4.0.5 on 2022-07-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='med',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='med',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
